### ISSUE TITLE
Track only for the script it is inserted in (more a question than an issue).

### ISSUE THREAD

**Issue by qpre** [TrackJs/Examples#2]
Hey !

I'm building a script that gets used by other people on other domains,
using this, would it be possible for me to only report errors coming from my script and not
the errors coming from the host page ?

Regards,

**Comment by toddhgardner** [comment]
Hey @qpre, unfortunately not :( The Tracking agent is setup to monitor a global document environment today. You could still use it in this environment and add ignore rules to filter out errors that are obviously not yours, but its not exactly a perfect fit.

I've thought a lot about this use case though, and I think it would be kind of intrusive to use. In order to capture telemetry, we would need a way to "namespace" the console, network, and visitor events that are relevant to your code. It would require your code to be built to directly interact with ours, which feels less compelling.

I'd love to learn more about your use case and if there is something we could do the help.
